### ISSUE TITLE
Hierarchical/recursive entities

### ISSUE THREAD

**Issue by maxott** [Permify/permify#375] opened 2023-04-07 04:47 UTC
**Is your feature request related to a problem? Please describe.**

I was trying to model a hierarchy of accounts when an account can have sub accounts which in turn can have sub accounts.
```
entity account {
    relation admin @user    
    relation member @user    
    relation parent_account @account

    action add_member = admin or parent_account.admin
    action delete_member = admin
} 
```
with 
```
account:1#admin@user:1
account:2#parent_account@account:1#...
account:3#parent_account@account:2#...
```

**Describe the solution you'd like**

```
can user:1 add_member account:3 => true
```

**Describe alternatives you've considered**

I guess the only alternative is to limit the number of levels or add business logic to add/remove respective tuples from
parent account

**Additional context**
[Playground.](https://play.permify.co/?s=0ay5urFJ81pptqWVl0qid)

**Comment by tolgaOzen** [comment] 2023-04-07 11:35
Hey @maxott, schema would need to be modified as follows for it to work as described:

```
entity user {}
        
entity account {
    relation admin @user    
    relation member @user    
    relation parent_account @account

    action add_member = admin or parent_account.parent_account.admin
    action delete_member = admin
} 
```

The reason we are doing it this way is because we need to first find the parent accounts of account:3 and then locate the admin.
 -> account:3 parent_account -> account:2
 -> is user:1 admin of the account:2 -> false

However, at present, we don't support 2 time nested relations (parent_account.parent_account.admin). But you could solve this by modifying the model as follows:

```
entity user {}
        
entity account {
    relation admin @user    
    relation member @user    
    relation parent_account @account

    action parent_admin = parent_account.admin
    
    action add_member = admin or parent_account.parent_admin
    action delete_member = admin
} 
```

I hope this helps! Let me know if you have any other questions.

you can check in out our playground: https://play.permify.co/?s=4uXLUOryS8gdQXsbDJfDH

**Comment by juanjoDiaz** [comment] 2023-04-07 15:11
Would that code work for 3 levels of nesting?
Or would it work for any nesting? e.g. 20 levels of subaccounts.

**Comment by tolgaOzen** [comment] 2023-04-07 18:04
Hi @juanjoDiaz , what are your thoughts on this solution? By establishing relationships, you can achieve the desired recursion.

**Schema**
```
entity user {}

entity account {
    relation super_admin @user
    relation admin @user @account#admin
    relation member @user @account#member
    
    action add_member = admin
    action delete_member = super_admin
} 
```

**Relationships**
- account:1#admin@user:1
- account:1#admin@account:2#admin
- account:2#admin@account:1#admin

you can check it out in our playground: https://play.permify.co/?s=JQl0wf3koQ5eDCZrcFR06

**Comment by juanjoDiaz** [comment] 2023-04-08 17:01
Hi @tolgaOzen ,

Thanks for the quick response!

That does not reflect the recursive nature of the permission on the schema but relies on the user modelling it using relationships.

To be honest I would expect that the schema provided by @maxott automatically expands the `parent_account.admin`.
So `which account user:1 can add_member` returns [1,2,3].
At the moment, it only return `[1]` which seems incorrect looking at the schema.

**Comment by tolgaOzen** [comment] 2023-04-08 18:09
Hi @juanjoDiaz, this seems to be a bug. The response should have been [1,2,3] as per the 
model provided. Our data filtering feature is in beta stage and therefore we apologize for the inconvenience. This issue will be resolved in version 0.3.8. Thank you for your understanding.

**Comment by juanjoDiaz** [comment] 2023-04-09 16:27
Thanks for acknowledging and fixing it quickly 🙂 

Similarly,
`can user:1 add_member account:1` returns `true` which is correct
`can user:1 add_member account:2` returns `true` which is correct
`can user:1 add_member account:3` returns `false` which is not correct.

**Comment by tolgaOzen** [comment] 2023-04-09 16:41
Indeed, the issue stems from the omission in the example I shared. I am providing the correct playground link as it should be.

link: https://play.permify.co/?s=63QxtTvQNAllPea-J4PMo

**Comment by juanjoDiaz** [comment] 2023-04-10 07:13
Hi @tolgaOzen ,

Thanks for the support.

I mean in the original schema:
```
entity account {
    relation admin @user    
    relation member @user    
    relation parent_account @account

    action add_member = admin or parent_account.admin
    action delete_member = admin
} 
```
[Playground.](https://play.permify.co/?s=0ay5urFJ81pptqWVl0qid)


With just one relationship defined:
- `account:1#admin@user:1`

I would expect that the recursion is followed through but it's not.

Looking at checks: 
- `can user:1 add_member account:1` => true ✅
- `can user:1 add_member account:2` => true ✅
- `can user:1 add_member account:3` => false ❌ (recursion is not happening here)

Or the same looking at data filtering:
`which account user:1 can add_member` => [1,2] ❌ (missing 3)

**Comment by tolgaOzen** [comment] 2023-04-10 08:15
Hi @juanjoDiaz, in this model, we need to manually establish the recursive relationship for parent_account.admin by using parent_account.parent_account.admin. Currently, we’re only allowing this for a single pass. Therefore, it may be more meaningful for your case to handle this through relationships. Additionally, we would love to learn more about your specific use case and discussing potential solutions together. Please feel free to book a time slot on our calendar using the following link: https://meetings-eu1.hubspot.com/ege-aytin.

**Comment by tolgaOzen** [comment] 2023-04-15 16:40
Hello @juanjoDiaz, we have resolved the bug in the data filtering feature and updated the playground. You can now test it again. Please let me know if you encounter any issues.

**Comment by juanjoDiaz** [comment] 2023-04-17 15:29
Hi @tolgaOzen ,

I still see the issue.

I'm looking at https://play.permify.co/?s=0ay5urFJ81pptqWVl0qid and getting the same results as above:

Looking at checks:

- can user:1 add_member account:1 => true ✅
- can user:1 add_member account:2 => true ✅
- can user:1 add_member account:3 => false ❌ (recursion is not happening here)

Or the same looking at data filtering:

- which account user:1 can add_member => [2,1] ❌ (The order of the numbers has changed but it's still missing 3)

**Comment by tolgaOzen** [comment] 2023-04-17 15:48
Hi @juanjoDiaz , yes, you're getting this result because the relationships here are incomplete; it's not a bug. You can check it out through this link: (https://play.permify.co/?s=63QxtTvQNAllPea-J4PMo).

**Comment by juanjoDiaz** [comment] 2023-04-17 15:59
Indeed.

We are getting confused here.
Going back to my previous comment. Such relationships would be hard to maintain if an account can have any number of subaccounts.
Let's say that 1 account have 4 levels and 5 subaccounts per level: That's 155 subaccounts.
This is not a crazy scenario. Think of a folder in the typical gDrive example instead of an accounts and the number is a lot larger.

I would have expected that this can be modelled. Something like
```
entity account {
    // roles 
    relation admin @user or parent_account.admin 
    relation member @user    
    relation parent_account @account

    action add_member = admin
    action delete_member = admin
} 
```
So the whole inheritance is automatically implicit in the model.

Does that make sense?

**Comment by tolgaOzen** [comment] 2023-04-17 16:11
Hi @juanjoDiaz  what are your thoughts on this model and its relationships? You can check it out here: https://play.permify.co/?s=km3-qWEGf8p1WsWSTNN-s.

**Comment by tolgaOzen** [comment] 2023-04-17 16:49
Could you please clear the cache for data filtering and try again?

**Comment by juanjoDiaz** [comment] 2023-04-18 06:44
I tried but now I only get `[1]`

**Comment by tolgaOzen** [comment] 2023-04-18 06:47
Can you please share me the playground link and assertions you tried?

**Comment by juanjoDiaz** [comment] 2023-04-18 07:48
Playground: https://play.permify.co/?s=LZRtIb_q44UWSwM5UAPc5

Checks:

- `user:1 add_member account:1` => true ✅
- `user:1 add_member account:2` => true ✅
- `user:1 add_member account:3` => true ✅

But incorrect data filtering:

- `which account user:1 can add_member` => [1] ❌

**Comment by tolgaOzen** [comment] 2023-04-18 08:20
@juanjoDiaz, could you please try it now?

**Comment by juanjoDiaz** [comment] 2023-04-19 06:59
That was fast!

`which account user:1 can add_member` => [1,3,2] ✅

The order is a bit odd but the result is correct.
Thanks!!

**Comment by EgeAytin** [comment] 2023-11-02 12:20
Closing this issue since it's completed.

**Closed by EgeAytin** 2023-11-02 12:20 UTC
Labels: area/schema
