### ISSUE TITLE
How to model indirect relationship that depends on an attribute?

### ISSUE THREAD

**Issue by juanjoDiaz** [Permify/permify#376] opened 2023-04-07 11:08 UTC
**Is your feature request related to a problem? Please describe.**

I can't figure out how to model indirect relationships that depend on an attribute?
This might be related to #375

Let's use the Google Drive example: you have users, folders and documents.
By default, when you have access to a folder, you have access to all the folders inside it.
I want to have a setting at folder level to enable visibility of subfolders, i.e.
Folder A is inside folder B and folder B has "subfolder visibility" set to true.
User X has access to Folder B. Thus, user X has access to folder A.
Folder B "subfolder visibility" set to false.
User X has access to folder B contents but it has no access to folder A contents.

**Describe the solution you'd like**

I would like to be able to use such kind of flag to limit recursion.

**Describe alternatives you've considered**

Use different entities depending on whether inheritance is enabled or not.
But it sounds like a terrible idea...

**Comment by tolgaOzen** [comment] 2023-04-07 11:51
Hey @juanjoDiaz , I wrote a comment on issue #375, in which I explained what I think your comment meant.

If you could clarify a bit more about what you meant by 'flag to limit recursion,' we would be happy to help.

**Comment by juanjoDiaz** [comment] 2023-04-07 15:13
Hi @tolgaOzen ,

Your comment clarifies how  to work around the shortcomings on recursive entities.
However it doesn't clarify how to "limit recursion"


Something like:

```
entity account {
    relation admin @user    
    relation member @user    
    relation parent_account @account

    attribute inherit_admin (true | false)

    action parent_admin = parent_account.admin
    
    action add_member = admin or (parent_account.inherit_admin == true and parent_account.parent_admin)
    action delete_member = admin
} 
```

**Comment by tolgaOzen** [comment] 2023-04-07 17:35
Hello @maxoss,

```
entity user {}
        
entity account {
    relation admin @user    
    relation member @user    
    relation parent_account @account

    action inherit_admin = parent_account.admin
    
    action add_member = admin or (inherit_admin and parent_account.inherit_admin)
    action delete_member = admin
} 
```
If you implement it this way, the desired feature will work as intended.
Additionally, the original message mentions that Attribute-Based Access Control (ABAC) is currently under development and will be launched soon.

**Comment by juanjoDiaz** [comment] 2023-04-08 17:04
Hi @tolgaOzen,

Thanks for the quick response!

I don't get `action inherit_admin = parent_account.admin`.
It seems that the account can inherit if the parent account has an admin which is not the intended behaviour.

The idea is that every account should have a boolean setting to inherit or not.

I guess that it's not possible to model something like that without ABAC.
Do you have any tentative ETA for ABAC to be available?

**Comment by tolgaOzen** [comment] 2023-04-08 18:49
Hi @juanjoDiaz , the feature you mentioned does require the ABAC (Attribute-Based Access Control) feature. We plan to release it in version 0.4.0. We are currently conducting tests, and it seems like it will take around 3 weeks to complete.

**Comment by juanjoDiaz** [comment] 2023-04-09 16:25
Awesome!

I think that I can wait for that 🙂

**Comment by EgeAytin** [comment] 2023-11-02 12:18
Hi @juanjoDiaz @tolgaOzen I'm closing this issue. Here is the related ABAC documentation: https://docs.permify.co/docs/use-cases/abac/

**Closed by EgeAytin** 2023-11-02 12:18 UTC
Labels: area/schema
